version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Requirements
          command: |
            set -e -x
            git submodule update --init
            sudo apt-get --yes install libboost-system-dev
            sudo -H pip install -r requirements.txt
      - run:
          name: Build
          command: python distribute.py
      - persist_to_workspace:
          root: dist
          paths:
            - "*"
      - run: cp -r www docs && cp dist/tailing.cc docs/
      - store_artifacts:
          path: docs/
          destination: gh-pages
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Requirements
          command: |
            set -e -x
            sudo apt-get --yes install libboost-system-dev
            sudo -H pip install -r requirements.txt
      - attach_workspace:
          at: dist
      - run:
          name: Test
          command: python test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - build
